version: '3'

tasks:
  compile-css:
    cmds:
      - npx @tailwindcss/cli -i ".\assets\css\tailwind.css" -o ".\public\css\styles.min.css" --minify --watch
  #    silent: true
  run-dev:
    cmds:
      - composer dev
  #    silent: true
  lint:
    cmds:
      - composer lint
    silent: true